version: "3"

services:
  api:
    container_name: api
    image: registry.hub.docker.com/andrewlucasgs/trabalho-individual-2020-1-api:latest
    ports:
      - 3000:3000
    depends_on:
      - postgres
    labels:
      - com.centurylinklabs.watchtower.enable=true
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create && rails db:migrate &&  bundle exec rails s -p 3000 -b '0.0.0.0'"

  postgres:
    image: postgres:11.4
    container_name: postgres
    restart: always
    environment: 
        POSTGRES_USER: ${POSTGRES_USER:-postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
        - pg_data:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    image: registry.hub.docker.com/andrewlucasgs/trabalho-individual-2020-1-frontend:latest
    ports:
      - '80:80'
    labels:
      - com.centurylinklabs.watchtower.enable=true


  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --cleanup true --debug true --interval 300 frontend api


volumes:
    pg_data: {}
