version: "3.8"

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./api:/api
    depends_on:
      - postgres
    command: rails server -b 0.0.0.0
    

  postgres:
    image: postgres:11.4
    container_name: postgres
    environment: 
        POSTGRES_USER: ${POSTGRES_USER:-postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
        - pg_data:/var/lib/postgresql/data

volumes:
    pg_data: {}
