name: CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ master ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose build
        
      - name: Prepare for testing
        run: |
          docker-compose run api rake db:create
          docker-compose run api rake db:migrate

      - name: Test
        run: docker-compose run api bundle exec rails test      
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  